/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Donation = IDL.Record({
  'donorName' : IDL.Text,
  'message' : IDL.Text,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'recordDonation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Donation = IDL.Record({
    'donorName' : IDL.Text,
    'message' : IDL.Text,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'recordDonation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };